### PR TITLE
Popup Bug Fixes and Refactor

### PR DESCRIPTION
**Pull request by drg101**
Fixed all the bugs I have found and refactored a bit.

@Marc-9 I didn't make the 'x' easier to access yet, because I'd like to let @honeybadgerofdoom finalize the styling of this before I put too much styling.

### CODE REVIEW

**Review by pierce-smith1 — CHANGES_REQUESTED** [review]
It does Fix:tm: the union issue, but some more problems I noticed that should be squashed for this bug fix PR:

~~If two sets disagree on how to format state or county, it seems the table just shows both:~~
image

Edit: This problem seems to actually just be happening to raw datasets, no need to even start a union:
image

Looking at tracts (in general, not necessarily over a union) reports the name of the tract as "County":
image

**Comment by drg101** [comment]
@pierce-smith1 I think I fixed all of the issues that you noted.

**Review by pierce-smith1 — APPROVED** [review]
LGTM
"Area name" is a tad clumsy but it will work for now.

**Review by Marc-9 — APPROVED** [review]
Do you guys think
LGTM = Looks Good To Me
or
LGTM = Lets Get inTo Master

Ive always read it as the ladder despite the fact I know its the former

**Comment by pierce-smith1** [comment]
> Do you guys think
> LGTM = Looks Good To Me
> or
> LGTM = Lets Get inTo Master
> 
> Ive always read it as the ladder despite the fact I know its the former

:sparkles: _why not both_ :sparkles:

**Pull request merged**
