### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by Marc-9**
Just a couple of small quality of life fixes, not all of them need to be changed though, and there are still some more things I would like to change.
So far I have altered the css for the menu so that the sliders don't go on top the the header, as well as alter the width and added some js to close the menu when the map is clicked on, but since queries are made every time the menu is closed this many not be wanted

### CODE REVIEW

**Comment by Marc-9** [comment]
When clicking on an icon or tract leaflet map no longer flies to it and alters bounds

**Comment by drg101** [comment]
Made the flyTo animation just go to the center of where the user clicks. This fixes the bug for the icons (on my end), whilst removing the zooming which I think was what was annoying about the old flyTo.

**Comment by drg101** [comment]
I think this allows the map to feel as "responsive" as possible whilst also being super simple.

**Review by drg101 — APPROVED** [review]
Everything seems to be an improvement, looks good.

**Pull request merged**
