### PR TITLE
Add license agreement to files

### PR DESCRIPTION
**Pull request by Marc-9**
Let me know if I missed any files, or if there are files in here that should not be
Also IntelliJ gave me tons of crud on this push, citing tons of warnings and some "errors" but it was unrelated to what I added lmk if we are just ignoring those or if I should try and fix those

### CODE REVIEW

**Comment by Marc-9** [comment]
For some reason it says I deleted lines?
This is a weird GH thing right?

**Comment by Marc-9** [comment]
Also current branches with new files will need the license, or just pm me when you merge into master and I can add them in with the script

**Review by pierce-smith1 — COMMENTED** [review]
Doesn't break anything:tm:
I'll need Daniel to weigh in on this, but some of the JS files are autogenerated, right? If so then putting comments on them is probably a bit of a waste and you may want to exclude them.
Also, I genuinely can't figure out when the diffs decide that a file has been completely deleted and re-written (causing GH to think there was deletions) or when a file has just had the license added to the top. It seems completely random.

**Comment by pierce-smith1** [comment]
> Also current branches with new files will need the license, or just pm me when you merge into master and I can add them in with the script

We could just require that any new PRs have licenses at the top of the files, to make things less work for you

**Comment by drg101** [comment]
The `src/js/grpc/GRPC_Querier/grpc_querier.bundle.js` should be excluded because it is autogenerated. Everything else looks fine.

**Review by drg101 — COMMENTED** [review]
See comment

**Comment by drg101** [comment]
> For some reason it says I deleted lines?
> This is a weird GH thing right?

This is just a git thing, it thinks you deleted the top of a lot of files, not just appended to them. idk why

**Review by drg101 — APPROVED** [review]

**Pull request merged**
