### PR TITLE
Added Soils Data

### PR DESCRIPTION
**Pull request by drg101**
Added soils data, it may be very slow to query for the next day or so because I still need to set up the indexing on it.

### CODE REVIEW

**Review by pierce-smith1 — CHANGES_REQUESTED** [review]
Dataset looks really cool! Some strange things:

* It looks like -0.1 is being used as a missing value and it's causing some UI oddities - is there a way you could deal with this without too much trouble?
image
* The name of the dataset isn't super descriptive, plus it could benefit from a help blurb describing what it is.
* This variable is kind of confusing: it sounds like a boolean on/off indicator but it has units?
image

**Comment by drg101** [comment]
> Dataset looks really cool! Some strange things:
> 
> * It looks like -0.1 is being used as a missing value and it's causing some UI oddities - is there a way you could deal with this without too much trouble?
>   image

Sadly not yet, it would cause other issues if I quickly set up the null value to be something else.

**Comment by drg101** [comment]
> * This variable is kind of confusing: it sounds like a boolean on/off indicator but it has units?
>   image

Yea not sure what is going on with this, I didn't download the data but I'll ask Saptashwa.

**Comment by drg101** [comment]
@pierce-smith1 Added some description and fixed 2d indexing, sadly the other things can't really be fixed right now.

**Comment by pierce-smith1** [comment]
Did you forget to push? I don't see any changes to the branch.

**Review by honeybadgerofdoom — APPROVED** [review]
Looks pretty good - ditto on @pierce-smith1's notes. Love the way this dataset visualizes with different color fields.

**Comment by drg101** [comment]
> Did you forget to push? I don't see any changes to the branch.

Oops, pushed now.

**Review by pierce-smith1 — APPROVED** [review]

**Pull request merged**
