### PR TITLE
Remove LegacyCode Folder

### PR DESCRIPTION
**Pull request by drg101**

### CODE REVIEW

**Review by Marc-9 — COMMENTED** [review]
what is the change to index.js?
u tryna sneak this in here???

**Review by Marc-9 — APPROVED** [review]
Finally.

**Comment by drg101** [comment]
> what is the change to index.js?
> u tryna sneak this in here???

There was a dependency in there for a legacycode thing lol.

**Review by honeybadgerofdoom — APPROVED** [review]
Looks good

**Review by tmoleary21 — APPROVED** [review]
Makes sense to me.

**Pull request merged**
