### PR TITLE
Standardizing Gradient

### PR DESCRIPTION
**Pull request by falarrieu**
Purpose of pull request is to standardize all gradients. Default gradient is to be blue for the lower bound, and red for the upper bound.

### CODE REVIEW

**Comment by tmoleary21** [comment]
Why are we getting rid of reverse gradient? Just curious.

**Comment by falarrieu** [comment]
Shrideep asked me to standardize all gradients to start in blue and to end in red. I would assume it would fall along the lines of users having the consistent understanding that blue is always the lower value.

**Comment by honeybadgerofdoom** [comment]
Did Shrideep ask to specifically remove the ability to set a reverse gradient?

We could achieve this PR with only the changes in `menumetadata.json`, without removing the _ability_ to set a reverse gradient in the future. Seeing as `reverseGradient` is something that needs to be specified in `menumetadata.json`, the default behavior would be blue=low, red=high.  I don't know if we should axe this feature completely unless Shrideep asked us to.

This looks good to me - just want to sort that out before we proceed.

**Comment by falarrieu** [comment]
It is now defaulted only by removing reverse gradient in menumetadata.json. What ideas to we have for it in the future?

**Review by honeybadgerofdoom — APPROVED** [review]
Looks great!

**Review by tmoleary21 — APPROVED** [review]

**Pull request merged**
