### PR TITLE
Random Lattice Num

### PR DESCRIPTION
**Pull request by drg101**
Added a `DEV` log which will tell you which machine you are connected to. I had to pass the number to the workers on config.

### CODE REVIEW

**Comment by drg101** [comment]
I added a backdoor to target specific servers. You can use it by setting `latticeNum` in localStorage as the lattice machine you want.

**Comment by pierce-smith1** [comment]
`SmartQuerier` is still hard-coded to `lattice-46` and port `27017`, is this an entirely different database?

**Review by pierce-smith1 — APPROVED** [review]
Approved on the condition that `lattice-46` still being hard-coded in SmartQuerier is intentional

**Comment by drg101** [comment]
Those statics don't get sent with the query anymore so they don't affect anything luckily.

**Pull request merged**
