### PR TITLE
New date selector 2

### PR DESCRIPTION
**Pull request by honeybadgerofdoom**

### CODE REVIEW

**Review by drg101 — CHANGES_REQUESTED** [review]
A few things:

- The menu can be crashed by removing all text in a picker
- The max time can be set before the min time, and vice-versa. Use the min/maxDate property to fix this. It is already set up for the other date picker.

**Review by drg101 — APPROVED** [review]
Wrong PR oops.

**Review by drg101 — CHANGES_REQUESTED** [review]
View original review

**Review by pierce-smith1 — COMMENTED** [review]
Will approve once Daniel's comments are fixed

**Comment by Marc-9** [comment]
Can you not select a day?
For neon 2d wind (safari) I can select a year and month but have no option for day

**Comment by honeybadgerofdoom** [comment]
@drg101 I am not able to set the min date before the max or vice-versa, and this branch does use the same minDate/maxDate logic as yours does. Which dataset are you noticing this for? Am working on the crash bug rn.

**Comment by honeybadgerofdoom** [comment]
@drg101 @pierce-smith1 those 2 bugs are fixed

**Comment by honeybadgerofdoom** [comment]
@Marc-9 some datasets have finer/coarser temporal resolution than others. Heatwaves, for example,  can only select year whereas many NEON datasets can select minutes.

**Review by drg101 — APPROVED** [review]
Works for me.

**Review by pierce-smith1 — APPROVED** [review]

**Pull request merged**
