### PR TITLE
React UI state refactor

### PR DESCRIPTION
**Pull request by honeybadgerofdoom**
Known issue: when you update the workspace, the state of all constraints is reset. I'm still working out the best way to fix this.  The constraints themselves persist, and if you have changed which constraints are active for a given layer that persists as well on workspace update.

This is still being refactored! Definitely a work in progress.

Making this PR to try and avoid/fix merge conflicts going forward.

### CODE REVIEW

**Review by drg101 — CHANGES_REQUESTED** [review]
Console errors when updating workspace should be fixed.

**Comment by honeybadgerofdoom** [comment]
@drg101 fixed console errors

**Comment by honeybadgerofdoom** [comment]
Admittedly putting this here mostly for my own reference as I've only just noticed it.

Constraints belonging to layers that are 'higher' (lower index) up in the workspace array persist on workspace update when layer(s) that were added/removed are 'lower' (higher index) on the workspace array. The inverse is not true.

**Review by drg101 — CHANGES_REQUESTED** [review]
I'm noticing a duplicate keys console error on the advanced popup.

**Review by drg101 — APPROVED** [review]

**Pull request merged**
