### PR TITLE
Matt chart control area

### PR DESCRIPTION
**Pull request by honeybadgerofdoom**

### CODE REVIEW

**Comment by pierce-smith1** [comment]
Looks good overall, but I hate that the histograms are shoved to the left. They should take up the whole area like scatterplots do. 
image
(I may be able to fix this myself just by committing directly to this branch if you don't mind)

**Review by pierce-smith1 — CHANGES_REQUESTED** [review]
See above

**Comment by pierce-smith1** [comment]
I made some tiny CSS changes to fit the histograms a little better. Let me know if it breaks anything on this branch

**Comment by honeybadgerofdoom** [comment]
@pierce-smith1 I agree that the graphs need some more TLC, but that's not really the scope of this PR. I'm trying to keep my PRs really specific - this one is just about the chart buttons allowing Users to create/delete charts and toggle the axes.

**Comment by honeybadgerofdoom** [comment]
@pierce-smith1 yeah those CSS changes look great

**Review by drg101 — APPROVED** [review]
Works for me

**Pull request merged**
