### PR TITLE
Lexicographic sort of advanced constraints

### LINKED ISSUE #460: Sort constraints in advanced tab

### PR DESCRIPTION
**Pull request by tmoleary21**
Overall, pretty simple additions. First pull request!

I added sorting in the `extractLayerConstraints` function in Layer.js because it is when the array of all of the layer constraints is first created. I originally tried sorting in the AdvancedConstraints component, but then there are issues with the index not matching between `allLayerConstraints`, `defaultLayerConstraints`, and `activeLayerConstraints`.

Closes #460

### CODE REVIEW

**Review by pierce-smith1 — COMMENTED** [review]
Not sure this is working as intended? (This is the Public Schools dataset)

image

**Comment by tmoleary21** [comment]
Uh oh, that is definitely not right. I'll mark this as a draft and see if I can figure out why it didn't work right.

**Comment by tmoleary21** [comment]
All right that should be fixed. Thank you for noticing it @pierce-smith1. The datasets I was using to test it weren't very representative of the whole. It now sorts by the label property instead of just name

**Review by pierce-smith1 — APPROVED** [review]
LGTM

**Pull request merged**
