### PR TITLE
Add NSF logo, with tooltip text, to lower-right of map

### PR DESCRIPTION
**Pull request by honeybadgerofdoom**
The idea here being that we can remove that footer from the /aperture page on the website, because it is problematic. TBH this actually looks a lot better than I thought it would.

Putting this up as a draft to see what y'all think, will confer with Shrideep Friday and see what he thinks.

### CODE REVIEW

**Comment by drg101** [comment]
I like this, tooltip text could be made bigger though. This makes aperture much more "portable," IE we (or anyone) can put the iFrame on any website and it still has the NSF blurb and such.

**Comment by honeybadgerofdoom** [comment]
> I like this, tooltip text could be made bigger though. This makes aperture much more "portable," IE we (or anyone) can put the iFrame on any website and it still has the NSF blurb and such.

That's a really good point.

**Comment by pierce-smith1** [comment]
Yeah, I'm a fan of how this looks and feels. Hopefully it can get approved.

**Comment by honeybadgerofdoom** [comment]
Shrideep approves

**Pull request merged**
