### PR TITLE
Defensive optimization

### PR DESCRIPTION
**Pull request by drg101**

### CODE REVIEW

**Comment by pierce-smith1** [comment]
It does Work:tm:, but some comments: 
- The cutoff for tracts seems a tad bit overaggressive - it could be zoomed out slightly (though knowing how coarse leaflet zoom levels are, not sure you can really make any minor adjustments to it)
- If you enable tracts at too far out of a zoom level, there seems to be extra latency between inputting a scroll and it actually scrolling in. Have you experienced this / do you know what this might be?
- Very minor formatting problems in the message - not every word should be capitalized, there's no period at the end.
That's all, the popup looks really nice.

**Review by pierce-smith1 — CHANGES_REQUESTED** [review]
see comment

**Comment by drg101** [comment]
@pierce-smith1 I addressed 1 and 3, I can't seem to replicate the zoom latency, but whenever I have run into that issue before though, so we should keep looking into it.

**Review by pierce-smith1 — APPROVED** [review]
Tract cap feels a lot better now - message is much better now too.
The zoom level issue feels like a deeper problem, we should make a GH issue for it - this can be merged in for now

**Pull request merged**
