### PR TITLE
gridMET time range goes up to yesterday

### PR DESCRIPTION
**Pull request by pierce-smith1**
Lets users select dates up to yesterday for the gridMET dataset, since we will very soon be updating it regularly.

### CODE REVIEW

**Comment by drg101** [comment]
Screenshot 2021-11-12 6 05 07 PM

**Comment by drg101** [comment]
I think this would be a better way to do it, just so that is standardized to the **start** of yesterday, instead of exactly 24 hours ago. It wont affect the functionality but it is more accurate in general.

**Review by drg101 — CHANGES_REQUESTED** [review]
See comment.

**Comment by pierce-smith1** [comment]
> I think this would be a better way to do it, just so that is standardized to the **start** of yesterday, instead of exactly 24 hours ago. It wont affect the functionality but it is more accurate in general.

I agree, this has been changed.

**Review by drg101 — APPROVED** [review]
Looks good to me.

**Pull request merged**
